imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-jammy

    dependencies:
        before:
            - curl -sS https://getcomposer.org/installer | php && mv composer.phar composer
        override:
            - ./composer install --no-scripts

    tests:
        override:
            - command: "./composer phpunit"
              coverage:
                  file: "docs/coverage.clover"
                  format: "php-clover"

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
