imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/bootstrap.php]

build:
    image: default-bionic

    nodes:
        analysis:
            project_setup:
                override:
                    - "composer install --no-interaction --no-scripts --no-plugins"
            tests:
                override:
                    - php-scrutinizer-run

    tests:
        override:
            - command: "vendor/bin/phpunit"
              coverage:
                  file: "docs/coverage.clover"
                  format: "php-clover"

tools:
    php_analyzer: true
    php_cpd: true
    php_mess_detector: true
    php_loc: true
    php_pdepend: true
