imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
            dependencies:
                before:
                    - curl -sS https://getcomposer.org/installer | php && mv composer.phar composer
                override:
                    - cd report && ../composer install --no-scripts
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

    tests:
        override:
            - command: "cd report && ../composer phpunit"
              coverage:
                  file: "report/docs/coverage.clover"
                  format: "php-clover"
